name       : python-peewee
version    : 3.5.1
release    : 3
source     :
    - https://github.com/coleifer/peewee/archive/3.5.1.tar.gz : 9b1ef00ce6e50507f1bf392d369e04d32c38510fc933b9bc90a24bca67105572
license    : MIT
component  : programming.python
summary    : A small, expressive orm -- supports postgresql, mysql and sqlite
description: |
    Peewee is a simple and small ORM. It has few (but expressive) concepts, making it easy to learn and intuitive to use.
builddeps  :
    - pkgconfig(sqlite3)
    - flask
    - cython
    - psycopg2
    - python-apsw
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 runtests.py
    popd
