name       : python-peewee
version    : 3.13.1
release    : 6
source     :
    - https://github.com/coleifer/peewee/archive/3.13.1.tar.gz : 225873f2066e3f2cf886b89d8a3c5d54aaaf276fb153c35c8fbd7eef16ed8ff2
license    : MIT
component  : programming.python
summary    : A small, expressive orm -- supports postgresql, mysql and sqlite
description: |
    Peewee is a simple and small ORM. It has few (but expressive) concepts, making it easy to learn and intuitive to use.
builddeps  :
    - pkgconfig(sqlite3)
    - flask
    - cython
    - psycopg2
    - python-apsw
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test runtests.py
