name       : python-peewee
version    : 3.7.1
release    : 4
source     :
    - https://github.com/coleifer/peewee/archive/3.7.1.tar.gz : d9b9b00dfd7eb0d3ad570a5c2a6a1a32a254bfcaf2d76d8066af7f79dbcda4cd
license    : MIT
component  : programming.python
summary    : A small, expressive orm -- supports postgresql, mysql and sqlite
description: |
    Peewee is a simple and small ORM. It has few (but expressive) concepts, making it easy to learn and intuitive to use.
builddeps  :
    - pkgconfig(sqlite3)
    - flask
    - cython
    - psycopg2
    - python-apsw
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test runtests.py
